### PR TITLE
Fix for GitHub public stats changes 

### PR DESCRIPTION
**Pull request by KCreate**
Hello again,

I have rewritten a big part of the code to make sure this works again. I've removed some dead code, eliminated underscore as a dependency and added some deprecation warnings.

I've also changed the documentation-method to JSDoc.

Please Tell me what you think about this.

screenshot 2016-06-06 at 13 53 47

### CODE REVIEW

**Comment by KCreate** [comment]
The latest commit just removed moment and underscore as a dependency.

**Comment by KCreate** [comment]
Are there any updates on wether this will be merged or not?

**Comment by thehhugg** [comment]
Yeah, I'd love to see this merged.

**Comment by fjahr** [comment]
@Shikkic I just used @KCreate 's fork in your gitbar project and it is working fine. You should merge the PR imo. If you don't want to maintain the project anymore just give notice so someone can take over. Gitbar is still promoted on the Bitbar website and I think it's a shame it's not working currently. Thanks!

**Comment by KCreate** [comment]
Hey @Shikkic, if you have no objections  I would love to maintain `Shikkic/gh-scrape` and `Shikkic/gitbar` . Please let me know what you think about this.

**Comment by KCreate** [comment]
:+1:

**Pull request merged**
